package com.nori.domain;

import static com.nori.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AlcoholAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlcoholAllPropertiesEquals(Alcohol expected, Alcohol actual) {
        assertAlcoholAutoGeneratedPropertiesEquals(expected, actual);
        assertAlcoholAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlcoholAllUpdatablePropertiesEquals(Alcohol expected, Alcohol actual) {
        assertAlcoholUpdatableFieldsEquals(expected, actual);
        assertAlcoholUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlcoholAutoGeneratedPropertiesEquals(Alcohol expected, Alcohol actual) {
        assertThat(actual)
            .as("Verify Alcohol auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlcoholUpdatableFieldsEquals(Alcohol expected, Alcohol actual) {
        assertThat(actual)
            .as("Verify Alcohol relevant properties")
            .satisfies(a -> assertThat(a.getAlcoholName()).as("check alcoholName").isEqualTo(expected.getAlcoholName()))
            .satisfies(a -> assertThat(a.getAlcoholType()).as("check alcoholType").isEqualTo(expected.getAlcoholType()))
            .satisfies(a -> assertThat(a.getBrandName()).as("check brandName").isEqualTo(expected.getBrandName()))
            .satisfies(a -> assertThat(a.getAbv()).as("check abv").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAbv()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlcoholUpdatableRelationshipsEquals(Alcohol expected, Alcohol actual) {
        // empty method
    }
}
