package com.nori.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DrinkLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkLogAllPropertiesEquals(DrinkLog expected, DrinkLog actual) {
        assertDrinkLogAutoGeneratedPropertiesEquals(expected, actual);
        assertDrinkLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkLogAllUpdatablePropertiesEquals(DrinkLog expected, DrinkLog actual) {
        assertDrinkLogUpdatableFieldsEquals(expected, actual);
        assertDrinkLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkLogAutoGeneratedPropertiesEquals(DrinkLog expected, DrinkLog actual) {
        assertThat(actual)
            .as("Verify DrinkLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkLogUpdatableFieldsEquals(DrinkLog expected, DrinkLog actual) {
        assertThat(actual)
            .as("Verify DrinkLog relevant properties")
            .satisfies(a -> assertThat(a.getDrinkDate()).as("check drinkDate").isEqualTo(expected.getDrinkDate()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getMemo()).as("check memo").isEqualTo(expected.getMemo()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkLogUpdatableRelationshipsEquals(DrinkLog expected, DrinkLog actual) {
        assertThat(actual)
            .as("Verify DrinkLog relationships")
            .satisfies(a -> assertThat(a.getAlcohol()).as("check alcohol").isEqualTo(expected.getAlcohol()))
            .satisfies(a -> assertThat(a.getPlace()).as("check place").isEqualTo(expected.getPlace()));
    }
}
