package com.nori.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceAllPropertiesEquals(Place expected, Place actual) {
        assertPlaceAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceAllUpdatablePropertiesEquals(Place expected, Place actual) {
        assertPlaceUpdatableFieldsEquals(expected, actual);
        assertPlaceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceAutoGeneratedPropertiesEquals(Place expected, Place actual) {
        assertThat(actual)
            .as("Verify Place auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceUpdatableFieldsEquals(Place expected, Place actual) {
        assertThat(actual)
            .as("Verify Place relevant properties")
            .satisfies(a -> assertThat(a.getPlaceName()).as("check placeName").isEqualTo(expected.getPlaceName()))
            .satisfies(a -> assertThat(a.getPlaceType()).as("check placeType").isEqualTo(expected.getPlaceType()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaceUpdatableRelationshipsEquals(Place expected, Place actual) {
        // empty method
    }
}
