openapi: 3.0.3
info:
  title: SakeLog API
  description: SakeLog お酒管理・飲酒記録API
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
paths:
  /drinklogs:
    post:
      summary: 飲酒記録登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrinkLogRequest"
      responses:
        "201":
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrinkLogResponse"

components:
  schemas:
    DrinkLogRequest:
      type: object
      properties:
        drinkId:
          type: integer
          format: int64
          description: お酒マスタID
        drinkDate:
          type: string
          format: date
          description: 飲酒日
        amountMl:
          type: integer
          description: 量(ml)
        rating:
          type: integer
          description: 評価（1〜5）
        comment:
          type: string
          description: コメント（感想）
      required:
        - drinkId
        - drinkDate
        - amountMl

    DrinkLogResponse:
      type: object
      properties:
        tDrinkLogId:
          type: integer
          format: int64
          description: 飲酒記録ID
        createdAt:
          type: string
          format: date-time
          description: 登録日時
      required:
        - tDrinkLogId
        - drinkId
