openapi: 3.0.3
info:
  title: SakeLog API
  description: SakeLog お酒管理・飲酒記録API（絞り込み版）
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
paths:
  /drinks:
    get:
      summary: お酒一覧取得
      responses:
        "200":
          description: お酒一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drink"
    post:
      summary: お酒登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrinkInput"
      responses:
        "201":
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Drink"

  /drinklogs:
    get:
      summary: 飲酒記録一覧取得
      responses:
        "200":
          description: 飲酒記録一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DrinkLog"
    post:
      summary: 飲酒記録登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DrinkLogInput"
      responses:
        "201":
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DrinkLog"

components:
  schemas:
    Drink:
      type: object
      properties:
        m_drink_id:
          type: integer
          format: int64
          description: お酒マスタID
        name:
          type: string
          description: 銘柄名
        category:
          type: string
          description: カテゴリー（例：ビール、日本酒）
        brand:
          type: string
          description: ブランド（メーカー・蔵元）
        abv:
          type: number
          format: float
          description: アルコール度数（％）
        country:
          type: string
          description: 原産国
        description:
          type: string
          description: 詳細説明
      required:
        - name
    DrinkInput:
      type: object
      properties:
        name:
          type: string
          description: 銘柄名
        category:
          type: string
          description: カテゴリー（例：ビール、日本酒）
        brand:
          type: string
          description: ブランド（メーカー・蔵元）
        abv:
          type: number
          format: float
          description: アルコール度数（％）
        country:
          type: string
          description: 原産国
        description:
          type: string
          description: 詳細説明
      required:
        - name
    DrinkLog:
      type: object
      properties:
        t_drinklog_id:
          type: integer
          format: int64
          description: 飲酒記録ID
        drink_id:
          type: integer
          format: int64
          description: お酒マスタID
        drink_date:
          type: string
          format: date
          description: 飲酒日
        amount_ml:
          type: integer
          description: 量(ml)
        rating:
          type: integer
          description: 評価（1〜5）
        comment:
          type: string
          description: コメント（感想）
      required:
        - drink_id
        - drink_date
        - amount_ml
    DrinkLogInput:
      type: object
      properties:
        drink_id:
          type: integer
          format: int64
          description: お酒マスタID
        drink_date:
          type: string
          format: date
          description: 飲酒日
        amount_ml:
          type: integer
          description: 量(ml)
        rating:
          type: integer
          description: 評価（1〜5）
        comment:
          type: string
          description: コメント（感想）
      required:
        - drink_id
        - drink_date
        - amount_ml
